# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pybar2000(object):
    def setupUi(self, Pybar2000):
        Pybar2000.setObjectName("Pybar2000")
        Pybar2000.resize(1109, 700)
        self.centralwidget = QtWidgets.QWidget(Pybar2000)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 130, 331, 421))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Artistas = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.Artistas.setObjectName("Artistas")
        self.horizontalLayout.addWidget(self.Artistas)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(380, 130, 331, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Albumes = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.Albumes.setObjectName("Albumes")
        self.horizontalLayout_2.addWidget(self.Albumes)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(740, 130, 311, 421))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Canciones = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.Canciones.setObjectName("Canciones")
        self.horizontalLayout_3.addWidget(self.Canciones)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 69, 331, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(380, 70, 331, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(740, 70, 311, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(440, 630, 181, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Play = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Play.setObjectName("Play")
        self.horizontalLayout_4.addWidget(self.Play)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(650, 630, 181, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Pause = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.Pause.setObjectName("Pause")
        self.horizontalLayout_5.addWidget(self.Pause)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(230, 630, 181, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.Stop.setObjectName("Stop")
        self.horizontalLayout_6.addWidget(self.Stop)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(740, 10, 311, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Volumen = QtWidgets.QSlider(self.horizontalLayoutWidget_7)
        self.Volumen.setOrientation(QtCore.Qt.Horizontal)
        self.Volumen.setObjectName("Volumen")
        self.horizontalLayout_7.addWidget(self.Volumen)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(621, 10, 91, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ToggleAudio = QtWidgets.QToolButton(self.horizontalLayoutWidget_8)
        self.ToggleAudio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI/UI/altavoz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ToggleAudio.setIcon(icon)
        self.ToggleAudio.setIconSize(QtCore.QSize(32, 20))
        self.ToggleAudio.setObjectName("ToggleAudio")
        self.horizontalLayout_8.addWidget(self.ToggleAudio)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(850, 630, 181, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Next = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.Next.setObjectName("Next")
        self.horizontalLayout_9.addWidget(self.Next)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(20, 630, 181, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Prev = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.Prev.setObjectName("Prev")
        self.horizontalLayout_10.addWidget(self.Prev)
        Pybar2000.setCentralWidget(self.centralwidget)

        self.retranslateUi(Pybar2000)
        QtCore.QMetaObject.connectSlotsByName(Pybar2000)

    def retranslateUi(self, Pybar2000):
        _translate = QtCore.QCoreApplication.translate
        Pybar2000.setWindowTitle(_translate("Pybar2000", "JcPlayer2020"))
        self.label.setText(_translate("Pybar2000", "Artistas"))
        self.label_2.setText(_translate("Pybar2000", "Albumes"))
        self.label_3.setText(_translate("Pybar2000", "Canciones"))
        self.Play.setText(_translate("Pybar2000", "Reproducir"))
        self.Pause.setText(_translate("Pybar2000", "Pausar"))
        self.Stop.setText(_translate("Pybar2000", "Parar"))
        self.Next.setText(_translate("Pybar2000", "Siguiente >>"))
        self.Prev.setText(_translate("Pybar2000", "<< Anterior"))
